var x= 50;
// document.write(x);
console.time("test");
console.log(x+30);
console.log([1,2,3]);
console.table([1,2,3]);
console.error("This is erorr");
console.warn("This is warning");
console.timeEnd("test");
// console.clear();